use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    central_repository_api::main()
}
